apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: ecommerce
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai1aR2VzWHppSTZPS3ZkWl9oMGMwUDlIb1p1Z3dxU1dxbjg1MDh2bmFZR1JwdDdYME9OcUNWOXJCSkpLOHotbW40U2JNVEJ2a1RfMlQzQmxia0ZKekdGZU5aZ1hma3p1ajl6NXJUR3RnaDFXWmRhbW52MjE3eFBPNFYxZWFpTW83Ry1qSkt4U1ZLMTZVNVhxZTQ2TXZkVk5qMjI0OEE=