name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config
        env:
          KUBECONFIG: ~/.kube/config    

      - name: Restart product-service
        run: kubectl rollout restart deployment/product-service -n ecommerce

      - name: Restart order-service
        run: kubectl rollout restart deployment/order-service -n ecommerce
